Skip test_fqdn when hostname resolution fails
When running the tests in containers without systemd,
hostname resolution can fail with:
socket.gaierror: [Errno -3] Temporary failure in name resolution

This is due to the generated hostname being either a random
string or the container ID which cannot be resolved to an IP address.

Skip the test if we fail to resolve the FQDN.